/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/math_lib_test.check" instead.
 */

#include <check.h>

#line 1 "tests/math_lib_test.check"
#include <stdlib.h>
#include <limits.h>
#include "../src/math_lib.h"

static const double ERROR_TOLERANCE = 1e-10;


START_TEST(sigmoid_test)
{
#line 10
	ck_assert_msg(fabs(sigmoid(INT_MIN) - 0) <= ERROR_TOLERANCE, "sigmoid failed at -inf");
	ck_assert_msg(fabs(sigmoid(0) - 0.5) <= ERROR_TOLERANCE, "sigmoid(0) should be 0.5");
	ck_assert_msg(fabs(sigmoid(INT_MAX) - 1) <= ERROR_TOLERANCE, "sigmoid failed at +inf");
	
}
END_TEST

START_TEST(bounded_sigmoid_test)
{
#line 15
	ck_assert_msg(fabs(bounded_sigmoid(INT_MIN, -10, 10) - (-10)) <= ERROR_TOLERANCE,
		"bounded_sigmoid failed at -inf");
	ck_assert_msg(fabs(bounded_sigmoid(0, 2, 4) - 3) <= ERROR_TOLERANCE,
		"bounded_sigmoid(0, 2, 4) should be 3.0");
	ck_assert_msg(fabs(bounded_sigmoid(INT_MAX, 0, 20) - 20) <= ERROR_TOLERANCE,
		"bounded_sigmoid failed at +inf");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("math_lib");
    TCase *tc1_1 = tcase_create("math_lib");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, sigmoid_test);
    tcase_add_test(tc1_1, bounded_sigmoid_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
